### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by moelkenzi** [dugsiiyeinc/community#138]
Dear Dugsiiye Team,  

I am a Computer Science student at Somali National University with a passion for open-source and tech innovation. I have worked on projects like *@BarePlatform* (launching soon) and others focused on empowering learners in technology. I am eager to collaborate and contribute to the community’s goals.  

Thank you for your consideration.  

Best regards,  
Elkenzi

**Comment by sharafdin** [comment]
Thank you for your interest in joining the Dugsiiye GitHub Community Organization! You have been invited, and you should soon receive an email or notification on GitHub to accept the invitation.

We are thrilled to have you on board and look forward to your contributions. Welcome to the community! Let's work together to make amazing things happen.

If you have any questions or need assistance, feel free to reach out.

Best regards,
Mr Sharafdin
